/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package so2;

import java.util.concurrent.Semaphore;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Sergio Barros
 */
public class entradas extends javax.swing.JFrame {

    /**
     * Creates new form entradas
     */
    public entradas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bArquivo = new javax.swing.JButton();
        arqNome = new javax.swing.JTextField();
        label = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        scan = new javax.swing.JTextPane();
        jScrollPane6 = new javax.swing.JScrollPane();
        fcfs = new javax.swing.JTextPane();
        jScrollPane7 = new javax.swing.JScrollPane();
        ssf = new javax.swing.JTextPane();
        jScrollPane8 = new javax.swing.JScrollPane();
        cscan = new javax.swing.JTextPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bArquivo.setText("Nome do Arquivo");
        bArquivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bArquivoActionPerformed(evt);
            }
        });
        getContentPane().add(bArquivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(182, 305, 167, -1));

        arqNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                arqNomeActionPerformed(evt);
            }
        });
        getContentPane().add(arqNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(182, 279, 167, -1));

        label.setText("Ultima solicitação do arquivo: "+max);
        label.setVisible(false);
        getContentPane().add(label, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        jLabel1.setText("Valor inválido, digite novamente");
        jLabel1.setVisible(false);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(182, 259, 167, -1));

        jLabel2.setText("FCFS");
        jLabel2.setVisible(false);
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        jLabel3.setText("SCAN");
        jLabel3.setVisible(false);
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, -1, -1));

        jLabel4.setText("C-SCAN");
        jLabel4.setVisible(false);
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(284, 209, -1, -1));

        jLabel5.setText("SSF");
        jLabel5.setVisible(false);
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 20, -1, -1));

        scan.setVisible(false);
        jScrollPane5.setViewportView(scan);
        jScrollPane5.setVisible(false);

        getContentPane().add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 230, 150));

        fcfs.setVisible(false);
        jScrollPane6.setViewportView(fcfs);
        jScrollPane6.setVisible(false);

        getContentPane().add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 230, 150));

        ssf.setVisible(false);
        jScrollPane7.setViewportView(ssf);
        jScrollPane7.setVisible(false);

        getContentPane().add(jScrollPane7, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 40, 230, 150));

        cscan.setVisible(false);
        jScrollPane8.setViewportView(cscan);
        jScrollPane8.setVisible(false);

        getContentPane().add(jScrollPane8, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 230, 230, 150));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    String nome;
    int mais,max;
    boolean x=true;
    Semaphore v =new Semaphore(0);
    public void label1v(){
        jLabel1.setVisible(true);
    }
    public void entrada1(){
        
        
        this.bArquivo.setText("Numero de Cilindros");
        this.label.setVisible(true);
        this.label.setText("Ultima solicitação do arquivo: "+mais);
        this.arqNome.setText("");
    }
    public void entrada2(){
        this.bArquivo.setText("Posição do Braço");
        
        this.label.setText("Ultima solicitação do arquivo: "+mais+" Ultimo Cilindro: "+max);
        this.arqNome.setText("");
    }
    public void entrada3(){
        this.bArquivo.setText("Tempo de Seek");
        this.arqNome.setText("");
    }
    public void fim(String fcfs,String ssf,String scan,String cscan){
        this.bArquivo.setVisible(false);
        //this.label.setVisible(false);
        this.arqNome.setVisible(false);
        this.fcfs.setVisible(true);
        this.ssf.setVisible(true);
        this.scan.setVisible(true);
        this.cscan.setVisible(true);
        this.jLabel2.setVisible(true);
        this.jLabel3.setVisible(true);
        this.jLabel4.setVisible(true);
        this.jLabel5.setVisible(true);
        this.fcfs.setText(fcfs);
        this.ssf.setText(ssf);
        this.scan.setText(scan);
        this.cscan.setText(cscan);
        this.jScrollPane6.setVisible(true);
        this.jScrollPane7.setVisible(true);
        this.jScrollPane8.setVisible(true);
        this.jScrollPane5.setVisible(true);
    }
    private void arqNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_arqNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_arqNomeActionPerformed

    private void bArquivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bArquivoActionPerformed
        jLabel1.setVisible(false);
        nome=arqNome.getText();
        v.release();

        //this.setVisible(false);

    }//GEN-LAST:event_bArquivoActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField arqNome;
    private javax.swing.JButton bArquivo;
    private javax.swing.JTextPane cscan;
    private javax.swing.JTextPane fcfs;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JLabel label;
    private javax.swing.JTextPane scan;
    private javax.swing.JTextPane ssf;
    // End of variables declaration//GEN-END:variables
}
